#:schema node_modules/wrangler/config-schema.json
name = "lucy-style"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".cloudflare"

[vars]
# Add environment variables here
# OPENROUTER_API_KEY = "..."

[site]
bucket = ".cloudflare"
